apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mood-ingress
spec:
  rules:
    - host: mood.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mood-tracker-service
                port:
                  number: 8080
